### ISSUE TITLE
Buff up docker

### ISSUE THREAD

**Issue by wonhyukchoi** [Barnard-PL-Labs/TSLSynthesizer#18]
Currently, `tsltools` is not inside the `docker` image yet.
Integrate `tsltools` inside docker so that users only need to install `npm` libraries.

**Comment by santolucito** [comment]
partial fix with https://github.com/Barnard-PL-Labs/tsl-strix-docker?

**Comment by wonhyukchoi** [comment]
@santolucito Yes, solved by https://github.com/Barnard-PL-Labs/tsl-strix-docker

**Comment by santolucito** [comment]
Is that image being used in this repo currently? Otherwise I think better to leave this open so I remember to pull it in

**Comment by wonhyukchoi** [comment]
@santolucito True, modified the installation script accordingly
